<script setup>
defineProps({
    stats: {
        type: Object,
        default: null,
    },
});

const formatDuration = (ms) => {
    if (ms == null || ! Number.isFinite(ms)) {
        return null;
    }

    if (ms < 1000) {
        return `${Math.round(ms)} ms`;
    }

    const seconds = ms / 1000;

    if (seconds < 60) {
        return `${seconds.toFixed(1)} s`;
    }

    const minutes = Math.floor(seconds / 60);
    const rest = seconds - minutes * 60;

    return `${minutes}m ${rest.toFixed(0)}s`;
};
</script>

<template>
    <div
        v-if="stats"
        class="mt-5 flex flex-col gap-1 text-xs text-gray-500 dark:text-gray-400"
    >
        <div class="flex flex-wrap items-baseline gap-x-3 gap-y-1">
            <span class="font-medium text-gray-600 dark:text-gray-300">Tokens</span>
            <span
                v-if="stats.questionTokens != null"
                title="Estimate for this user message only (~4 chars/token)"
            >
                question ≈ {{ stats.questionTokens }}
            </span>
            <span
                v-if="stats.inputTokens != null"
                title="Actual prompt tokens from the model (system + history + this message + tool definitions when tools were sent)"
            >
                prompt {{ stats.inputTokens }}
            </span>
            <span
                v-else-if="stats.promptTokensEstimated != null"
                title="Estimated full prompt (system + history + this message + tool definitions)"
            >
                prompt ≈ {{ stats.promptTokensEstimated }}
            </span>
            <span
                v-if="stats.toolsTokensEstimated != null"
                title="Estimated tokens for MCP/tool definitions sent with this request"
            >
                tools ≈ {{ stats.toolsTokensEstimated }}
            </span>
            <span
                v-if="stats.historyTokens != null && (stats.inputTokens != null || stats.promptTokensEstimated != null)"
                title="Approximate history + system share of the prompt (prompt − question − tools)"
            >
                history ≈ {{ stats.historyTokens }}
            </span>
            <span
                v-if="stats.outputTokens != null"
                title="Completion tokens generated by the model"
            >
                output {{ stats.outputTokens }}
            </span>
            <span
                v-if="stats.reasoningTokens != null"
                title="Tokens used for reasoning / thinking"
            >
                reasoning {{ stats.reasoningTokens }}
            </span>
            <span
                v-if="stats.answerTokens != null"
                title="Output tokens that are the visible answer (output − reasoning)"
            >
                answer {{ stats.answerTokens }}
            </span>
            <span
                v-if="stats.totalTokens != null"
                title="prompt + output"
            >
                total {{ stats.totalTokens }}
            </span>
            <span
                v-if="stats.usageSource === 'client' && stats.inputTokens == null && stats.outputTokens == null"
                class="italic opacity-70"
                title="Upstream did not return token usage for this stream"
            >
                (no usage from model)
            </span>
        </div>
        <div class="flex flex-wrap items-baseline gap-x-3 gap-y-1">
            <span class="font-medium text-gray-600 dark:text-gray-300">Timing</span>
            <span
                v-if="stats.elapsedMs != null"
                title="Total generation time from request start to stream end"
            >
                {{ formatDuration(stats.elapsedMs) }}
            </span>
            <span
                v-if="stats.tokensPerSecond != null"
                title="Output tokens per second"
            >
                {{ Number(stats.tokensPerSecond).toFixed(1) }} tok/s
            </span>
            <span
                v-if="stats.ttftMs != null"
                title="Time to first token"
            >
                TTFT {{ formatDuration(stats.ttftMs) }}
            </span>
        </div>
    </div>
</template>
